apps/authentication/urls.py
# -*- encoding: utf-8 -*-
"""
Copyright (c) 2019 - present AppSeed.us
"""

from django.urls import path
from .views import login_view, register_user, activate, email_confirm
from django.contrib.auth import views as auth_views  #<-- Changed
from django.urls import reverse_lazy

app_name = "authentication"

urlpatterns = [
    path('login/', login_view, name="login"),
    path('register/', register_user, name="register"),
    path("logout/", auth_views.LogoutView.as_view(), name="logout"),

    path("password-reset/", auth_views.PasswordResetView.as_view(template_name="accounts/password_templates/password_recovery.html",
                                                      email_template_name="accounts/password_templates/password_reset_email.html",
                                                      success_url = reverse_lazy("authentication:password_reset_done")),
                                                      name="password_reset"),

    path('password-reset/done', auth_views.PasswordResetDoneView.as_view(template_name='accounts/password_templates/password_reset_done.html'), name='password_reset_done'),

    path('reset/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(success_url=reverse_lazy("authentication:password_reset_complete"),
                                                                                template_name='accounts/password_templates/password_reset_confirm.html'),
                                                                                name='password_reset_confirm'),

    path('reset/done/', auth_views.PasswordResetCompleteView.as_view(template_name='accounts/password_templates/password_reset_complete.html'), name='password_reset_complete'),

    path('activate/<uidb64>/<token>', activate, name='activate'),

    path('email_confirm/<str:username>/', email_confirm, name='email_confirm'),
]

core/urls.py
# -*- encoding: utf-8 -*-
"""
Copyright (c) 2019 - present AppSeed.us
"""

from django.contrib import admin
from django.urls import path, include  # add this

urlpatterns = [
    path('admin/', admin.site.urls),          # Django admin route
    path("", include("apps.authentication.urls")), # Auth routes - login / register
    path("", include("apps.home.urls"))             # UI Kits Html files
]

apps/templates/accounts/password_templates/password_recovery.html
{% extends "layouts/base.html" %}

{% block title %} Password Reset {% endblock %} 

<!-- Specific Page CSS goes HERE  -->
{% block stylesheets %}{% endblock stylesheets %}

{% block content %}

  <div class="row">
    <div class="col-md-5">
      <div class="card">
        <div class="card-header card-header-primary">
          <h4 class="card-title">
            Password Recovery
          </h4>
        </div>
        <div class="card-body">

          <h6 class="card-category">
              {% if msg %}
                <span class="text-danger">{{ msg | safe }}</span>
              {% else %}
                  Enter your email address below
              {% endif %}  
          </h6>
          
          <br />

          <form role="form" method="post" action="">
              
            {% csrf_token %} 

            <div class="row">
              <div class="col-md-12">
                <div class="form-group">
                  <label class="bmd-label-floating">Email address</label>
                  <br>
                  {{ form.email }}
                </div>
              </div>
            </div>


            <button type="submit" name="login" class="btn btn-primary pull-left">Send email</button>

            <!-- &nbsp; &nbsp; 

            <div class="clearfix"></div> -->

          </form>
        </div>
      </div>
    </div>
  </div>

{% endblock content %}

<!-- Specific Page JS goes HERE  -->
{% block javascripts %}{% endblock javascripts %}

apps/templates/accounts/password_templates/password_reset_complete.html
{% extends "layouts/base.html" %}

{% block title %} Password reset complete {% endblock %} 

{% block content %}

<div class="row justify-content-center">
    <div class="col-md-5">
        <div class="card">
            <div class="card-header card-header-primary text-center">
                <h4 class="card-title">
                    Password changed
                </h4>
            </div>
            <div class="card-body text-center">

                <h6 class="card-category">
                    Your password has been set. You may go ahead and log in now.
                </h6>

                <a href="{% url 'authentication:login' %}" class="btn btn-primary mt-4">
                    Log in
                </a>
            </div>
        </div>
    </div>
</div>



{% endblock content %}

apps/templates/accounts/password_templates/password_reset_confirm.html
{% extends "layouts/base.html" %}

{% block title %} Password reset confirm {% endblock %} 

{% block content %}

{% if validlink %}

<div class="row justify-content-center">
    <div class="col-md-5">
        <div class="card">
            <div class="card-header card-header-primary text-center">
                <h4 class="card-title">
                    Enter new password
                </h4>
            </div>
            <div class="card-body text-center">

                <h6 class="card-category">
                    Please enter your new password twice so we can verify you typed it in correctly.
                </h6>
                <form method="post">
                    {% csrf_token %}
                    <div class="row">
                        <div class="col-md-12">
                          <div class="form-group">
                            <label class="bmd-label-floating">New password</label>
                            {{ form.new_password1 }}
                            {% if form.new_password1.errors %}
                                <p class="text-danger">{{ form.new_password1.errors }}</p>
                            {% endif %}
                          </div>
                        </div>
                    </div>

                    <br>

                    <div class="row">
                        <div class="col-md-12">
                          <div class="form-group">
                            <label class="bmd-label-floating">Confirm password</label>
                            {{ form.new_password2 }}
                            {% if form.new_password2.errors %}
                                <p class="text-danger">{{ form.new_password2.errors }}</p>
                            {% endif %}
                          </div>
                        </div>
                    </div>
                

                    <button type="submit" class="btn btn-primary mt-4">
                        Change password
                    </button>
                </form>
            </div>
        </div>
    </div>
</div>

{% endif %}

{% endblock content %}

apps/templates/accounts/password_templates/password_reset_done.html
{% extends "layouts/base.html" %}

{% block title %} Email confirmation {% endblock %} 

{% block content %}

<div class="row justify-content-center">
    <div class="col-md-5">
        <div class="card">
            <div class="card-header card-header-primary text-center">
                <h4 class="card-title">
                    Check your email
                </h4>
            </div>
            <div class="card-body text-center">

                <h6 class="card-category">
                    We've sent you an email with instructions for setting your new password, if an account exists with this email.
                </h6>

                <h6 class="card-category mt-4 mb-0">
                    Please check your inbox, and if you don't see the email, also check your spam folder.
                </h6>

                <h6 class="card-category mt-4 mb-0">
                    If you encounter any issues, <a href="#">contact</a> our support team. 
                </h6>

                <a href="{% url 'authentication:password_reset' %}" class="btn btn-primary mt-4">
                    Resend Confirmation Email
                </a>
            </div>
        </div>
    </div>
</div>



{% endblock content %}

apps/templates/accounts/password_templates/password_reset_email.html
{% load i18n %}{% autoescape off %}
Hi! We're sending this email because you requested a password reset for your user account at {{ site_name }}

Please go to the following page and choose a new password:
{% block reset_link %}
{{ protocol }}://{{ domain }}{% url 'authentication:password_reset_confirm' uidb64=uid token=token %}
{% endblock %}

Your username, in case you’ve forgotten: {{ user.get_username }}

Thanks for using our site!

The {{ site_name }} team

{% endautoescape %}