apps/authentication/urls.py
# -*- encoding: utf-8 -*-
"""
Copyright (c) 2019 - present AppSeed.us
"""

from django.urls import path
from .views import login_view, register_user, activate, email_confirm
from django.contrib.auth import views as auth_views  #<-- Changed
from django.urls import reverse_lazy

app_name = "authentication"

urlpatterns = [
    path('login/', login_view, name="login"),
    path('register/', register_user, name="register"),
    path("logout/", auth_views.LogoutView.as_view(), name="logout"),

    path("password-reset/", auth_views.PasswordResetView.as_view(template_name="accounts/password_templates/password_recovery.html",
                                                      email_template_name="accounts/password_templates/password_reset_email.html",
                                                      success_url = reverse_lazy("authentication:password_reset_done")),
                                                      name="password_reset"),

    path('password-reset/done', auth_views.PasswordResetDoneView.as_view(template_name='accounts/password_templates/password_reset_done.html'), name='password_reset_done'),

    path('reset/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(success_url=reverse_lazy("authentication:password_reset_complete"),
                                                                                template_name='accounts/password_templates/password_reset_confirm.html'),
                                                                                name='password_reset_confirm'),

    path('reset/done/', auth_views.PasswordResetCompleteView.as_view(template_name='accounts/password_templates/password_reset_complete.html'), name='password_reset_complete'),

    path('activate/<uidb64>/<token>', activate, name='activate'),

    path('email_confirm/<str:username>/', email_confirm, name='email_confirm'),
]

core/urls.py
# -*- encoding: utf-8 -*-
"""
Copyright (c) 2019 - present AppSeed.us
"""

from django.contrib import admin
from django.urls import path, include  # add this

urlpatterns = [
    path('admin/', admin.site.urls),          # Django admin route
    path("", include("apps.authentication.urls")), # Auth routes - login / register
    path("", include("apps.home.urls"))             # UI Kits Html files
]

apps/templates/accounts/inactive_user.html
{% extends "layouts/base.html" %}

{% block title %} Inactive user {% endblock %} 

<!-- Specific Page CSS goes HERE  -->
{% block stylesheets %}{% endblock stylesheets %}

{% block content %}

<div class="row justify-content-center">
    <div class="col-md-5">
        <div class="card">
            <div class="card-header card-header-primary text-center">
                <h4 class="card-title">
                    Email confirmation
                </h4>
            </div>
            <div class="card-body text-center">

                <h6 class="card-category">
                    We've sent you an email in order to activate your account.
                </h6>

                <h6 class="card-category mt-4 mb-0">
                    Please check your inbox, and if you don't see the email, also check your spam folder.
                </h6>

                <h6 class="card-category mt-4 mb-0">
                    If you encounter any issues, <a href="#">contact</a> our support team. 
                </h6>

                <a href="{% url 'authentication:login' %}" class="btn btn-primary mt-4">
                    Log in
                </a>
            </div>
        </div>
    </div>
</div>



{% endblock content %}

apps/templates/accounts/login.html
{% extends "layouts/base.html" %}

{% block title %} Login {% endblock %} 

<!-- Specific Page CSS goes HERE  -->
{% block stylesheets %}{% endblock stylesheets %}

{% block content %}
  {% if messages %}
  <ul class="messages">
      {% for message in messages %}
      <li{% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</li>
      {% endfor %}
  </ul>
  {% endif %}

  <div class="row">
    <div class="col-md-5">
      <div class="card">
        <div class="card-header card-header-primary">
          <h4 class="card-title">
            Login
          </h4>
        </div>
        <div class="card-body">

          <h6 class="card-category">
              {% if msg %}
                <span class="text-danger">{{ msg | safe }}</span>
              {% else %}
                  Add your credentials
              {% endif %}  
          </h6>
          
          <br />

          <form role="form" method="post" action="">
              
            {% csrf_token %} 

            <div class="row">
              <div class="col-md-12">
                <div class="form-group">
                  <label class="bmd-label-floating">Username</label>
                  {{ form.username }}
                </div>
              </div>
            </div>

            <br />

            <div class="row">
              <div class="col-md-12">
                <div class="form-group">
                  <label class="bmd-label-floating">Password</label>
                  {{ form.password }}
                </div>
              </div>
            </div>

            <br />

            <button type="submit" name="login" class="btn btn-primary pull-left">Login</button>

            &nbsp; &nbsp; 
            <span class="pull-right">
              Don't have an account? <a href="{% url 'authentication:register' %}" class="text-primary">Create</a><br>
              Forgot you password? <a href="{% url 'authentication:password_reset' %}">Reset it here</a>
            </span>
            

            <div class="clearfix"></div>

          </form>
        </div>
      </div>
    </div>
  </div>

{% endblock content %}

<!-- Specific Page JS goes HERE  -->
{% block javascripts %}{% endblock javascripts %}

apps/templates/accounts/register.html
{% extends "layouts/base.html" %}

{% block title %} Register {% endblock %} 

<!-- Specific Page CSS goes HERE  -->
{% block stylesheets %}{% endblock stylesheets %}

{% block content %}

  <div class="row">
    <div class="col-md-5">
      <div class="card">
        <div class="card-header card-header-primary">
          <h4 class="card-title">
            Create Account
          </h4>
        </div>
        <div class="card-body">

          <h6 class="card-category">
            Add your credentials
          </h6>
          
          <br />

            <form role="form" method="post" action="">
                
              {% csrf_token %} 

              <div class="row">
                <div class="col-md-12">
                  <div class="form-group">
                    <label class="bmd-label-floating">Username</label>
                    {{ form.username }}
                  </div>
                </div>
              </div>
              <span class="text-danger">{{ form.username.errors }}</span>

              <br />

              <div class="row">
                <div class="col-md-12">
                  <div class="form-group">
                    <label class="bmd-label-floating">Email</label>
                    {{ form.email }}
                  </div>
                </div>
              </div>
              <span class="text-danger">{{ form.email.errors }}</span>

              <br />

              <div class="row">
                <div class="col-md-12">
                  <div class="form-group">
                    <label class="bmd-label-floating">Password</label>
                    {{ form.password1 }}
                  </div>
                </div>
              </div>
              <span class="text-danger">{{ form.password1.errors }}</span>

              <br />

              <div class="row">
                <div class="col-md-12">
                  <div class="form-group">
                    <label class="bmd-label-floating">Password Check</label>
                    {{ form.password2 }}
                  </div>
                </div>
              </div>
              <span class="text-danger">{{ form.password2.errors }}</span>

              <br />

              <button type="submit" name="register" class="btn btn-primary pull-left">Register</button>

              &nbsp; &nbsp; 
              <span class="pull-right">
                Have an account? <a href="{% url 'authentication:login' %}" class="text-primary">Login</a>
              </span>

              <div class="clearfix"></div>

            </form>

        </div>
      </div>
    </div>
  </div>

{% endblock content %}

<!-- Specific Page JS goes HERE  -->
{% block javascripts %}{% endblock javascripts %}

apps/templates/accounts/template_activate_account.html
{% autoescape off %}
Hi {{ user }}

Please click on the link below to confirm you registration:

{{ Protocol }}://{{ domain }}{% url 'authentication:activate' uidb64=uid token=token %}
{% endautoescape %}